### ISSUE TITLE
ETA & Destination Sensor

### ISSUE THREAD

**Issue by wjbeckett** [bruhautomation/BRUH2-Home-Assistant-Configuration#1]
Just found your config and love it!
Was wondering though how you are able to get your Destination and ETA sensors?
What are they pulling the navigation data from?

**Comment by brusc** [comment]
Sorry I missed this until now! So I am pulling destination and ETA from Google Maps via Tasker on my Android Phone. It works great, but I think the last GMaps updated changed the notification format and I still need to sit down and straighten it out. Once I do, I'll get it uploaded to my GitHub! In the meantime, you can probably replicate it yourself pretty easily. I utilize the Notification Listener plugin and manipulate the ETA notification via a few var chop events. 

P.S. Now that there is the time travel component, this might be unnecessarily complicated. You could easily trigger home assistant to say you are on the way home and have it announce your ETA from that component directly rather than passing it in via a HTTP sensor. Stuff to play with! :+1:
